server:
  port: 9999
  servlet:
    context-path: /withdraw

mybatis-plus:
  type-aliases-package: com.shinewonder.model.withdraw.bean,com.shinewonder.model.withdraw.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.204.228:3466/linkinq?serverTimezone=Hongkong&useSSL=false
    username: root
    password: s2GNHRE3@1G*tTF3

  redis:
    host: 39.107.204.228
    port: 63359
    database: 0
    timeout: 1800000
    password: 69e87a96-5251-67d7-2455-7633118a5661
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
