//写流水线的脚本(声明式、脚本式)

pipeline{
    //全部的CICD流程都需要在这里定义

    //任何一个代理可用就可以执行

    //定义一些环境信息

    //定义流水线的加工流程

    //流水线的所有阶段
    states{
    //1.编译
        stage("代码编译"){
            steps{
                echo "编译..."
            }
        }
    //2.测试
        stage("代码测试"){
            steps{
                echo "测试..."
            }
        }
    //3.打包
        stage("代码打包"){
            steps{
                 echo "打包..."
            }
        }
    //4.部署
        stage("代码部署"){
            steps{
                echo "部署..."
            }
        }
    }
    agent any
}